apiVersion: v1
kind: Secret
metadata:
  name: mini-fintickstreams-secrets
type: Opaque
stringData:
  SHARD_MAIN_DSN: "postgres://user:pass@timescaledb:5432/dbname?sslmode=require"
  REDIS_NODE_A: "redis://redis:6379"
