apiVersion: v1
kind: Secret
metadata:
  name: mini-fintickstreams-secrets
type: Opaque
stringData:
  SHARD_MAIN_DSN: "postgresql://K@e{8gW|5#69@pg-postgresql:5432/DBNAME?sslmode=disable"
  REDIS_NODE_A: "redis://redis:6379"
